# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import routing_processor_pb2 as routing__processor__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in routing_processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoutingProcessorStub(object):
    """===== Services =====

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExternalProcess = channel.stream_stream(
                '/routing_processor.v1alpha1.RoutingProcessor/ExternalProcess',
                request_serializer=routing__processor__pb2.ProcessingRequest.SerializeToString,
                response_deserializer=routing__processor__pb2.ProcessingResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/routing_processor.v1alpha1.RoutingProcessor/GetCapabilities',
                request_serializer=routing__processor__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=routing__processor__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)


class RoutingProcessorServicer(object):
    """===== Services =====

    """

    def ExternalProcess(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutingProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExternalProcess': grpc.stream_stream_rpc_method_handler(
                    servicer.ExternalProcess,
                    request_deserializer=routing__processor__pb2.ProcessingRequest.FromString,
                    response_serializer=routing__processor__pb2.ProcessingResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=routing__processor__pb2.CapabilitiesRequest.FromString,
                    response_serializer=routing__processor__pb2.CapabilitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routing_processor.v1alpha1.RoutingProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('routing_processor.v1alpha1.RoutingProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoutingProcessor(object):
    """===== Services =====

    """

    @staticmethod
    def ExternalProcess(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/routing_processor.v1alpha1.RoutingProcessor/ExternalProcess',
            routing__processor__pb2.ProcessingRequest.SerializeToString,
            routing__processor__pb2.ProcessingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routing_processor.v1alpha1.RoutingProcessor/GetCapabilities',
            routing__processor__pb2.CapabilitiesRequest.SerializeToString,
            routing__processor__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SemanticCacheServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchCache = channel.unary_unary(
                '/routing_processor.v1alpha1.SemanticCacheService/SearchCache',
                request_serializer=routing__processor__pb2.SearchRequest.SerializeToString,
                response_deserializer=routing__processor__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.StoreChat = channel.unary_unary(
                '/routing_processor.v1alpha1.SemanticCacheService/StoreChat',
                request_serializer=routing__processor__pb2.StoreChatRequest.SerializeToString,
                response_deserializer=routing__processor__pb2.StoreChatResponse.FromString,
                _registered_method=True)


class SemanticCacheServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticCacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchCache': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCache,
                    request_deserializer=routing__processor__pb2.SearchRequest.FromString,
                    response_serializer=routing__processor__pb2.SearchResponse.SerializeToString,
            ),
            'StoreChat': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreChat,
                    request_deserializer=routing__processor__pb2.StoreChatRequest.FromString,
                    response_serializer=routing__processor__pb2.StoreChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routing_processor.v1alpha1.SemanticCacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('routing_processor.v1alpha1.SemanticCacheService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticCacheService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routing_processor.v1alpha1.SemanticCacheService/SearchCache',
            routing__processor__pb2.SearchRequest.SerializeToString,
            routing__processor__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routing_processor.v1alpha1.SemanticCacheService/StoreChat',
            routing__processor__pb2.StoreChatRequest.SerializeToString,
            routing__processor__pb2.StoreChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
