llmRequestCosts:
- metadataKey: used_token
  type: InputToken
metadataNamespace: ai_gateway_llm_ns
modelNameHeaderKey: x-model-name
rules:
- backends:
  - name: moc
    auth:
      apiKey:
        filename: /tmp/nerc-open-ai-api-key
    schema:
      name: OpenAI
    weight: 1
    endpoint: https://mixtral-mixtral-serve.apps.ocp-beta-test.nerc.mghpcc.org/v1 # MOC
    autoModelConfig:
      semanticProcessorServiceURL: http://localhost:8000/analyze
      simpleModels:
      - mixtral
      strongModels:
      - mixtral
  headers:
  - name: x-model-name
    value: mixtral
schema:
  name: OpenAI
selectedBackendHeaderKey: x-selected-backend-name
