llmRequestCosts:
- metadataKey: used_token
  type: InputToken
metadataNamespace: ai_gateway_llm_ns
modelNameHeaderKey: x-model-name
rules:
- backends:
  - auth:
      apiKey:
        filename: /tmp/open-ai-api-key
    name: openai
    schema:
      name: OpenAI
    weight: 0
    autoModelConfig:
      semanticProcessorServiceURL: http://localhost:8000/analyze
      simpleModels:
      - gpt-3.5-turbo
      strongModels:
      - gpt-4o-mini
  headers:
  - name: x-model-name
    value: gpt-3.5-turbo
  - name: x-model-name
    value: gpt-4o-mini
schema:
  name: OpenAI
selectedBackendHeaderKey: x-selected-backend-name
